### ISSUE TITLE
Is there any reason this isn't published on dockerhub?

### ISSUE THREAD

**Issue by rossdargan** [fxleblanc/rsync-vps#1]
It's really useful, so I was just wondering why you didn't publish it on dockerhub?

**Comment by fxleblanc** [comment]
None, except my negligence. Thanks for pointing that out.

[https://hub.docker.com/r/petitprince/rsync-vps/](url)

**Comment by rossdargan** [comment]
Awesome stuff - only other suggestion I'd make is look into automatic builds. It gives people more confidence that the code you have up there is the same as what's here :)

As it happens I've ended up taken what you have done and rebased it on filebot so I can run a script after the rsync - but thanks for sharing what you have done!
